name: Staging Deployment

on:
  push:
    branches:
    - main

jobs:
  docker_deploy:
    name: Docker Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: |
          touch .env
          echo GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }} >> .env
          cat .env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to stage environment
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          provenance: false
          tags: savalite/images:safecityng-uimobile-stage
          build-args: REPOSITORY=savalite/images:safecityng-uimobile-stage 